environments:
  prod:
    values:
    - environments/prod/values.yaml

helmfiles:
- path: common/cert-manager/helmfile.yaml.gotmpl
  values:
  - {{ toYaml .Environment.Values | nindent 4 }}
- path: common/basic-auth/helmfile.yaml.gotmpl
  values:
  - {{ toYaml .Environment.Values | nindent 4 }}
- path : common/cluster-autoscaler/helmfile.yaml.gotmpl
  values:
  - {{ toYaml .Environment.Values | nindent 4 }}
- path : common/nginx-ingress/helmfile.yaml.gotmpl
  values:
  - {{ toYaml .Environment.Values | nindent 4 }}
