name: Main
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
  create-envfile: 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_SHOPIFY_API_KEY: "858b5e471ef9a7506863936f0a5c05b6"
        envkey_SHOPIFY_API_SECRET: "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"
        envkey_SHOP: "hotbotstore.myshopify.com"
        envkey_SCOPES: "read_products,read_customers,read_orders,read_order_edits,read_draft_orders,read_fulfillments,read_shipping,read_inventory"
        envkey_HOST: "https://botnot0124.herokuapp.com"
        envkey_BOTNOT_API_URL: "https://3jak1c5zra.execute-api.us-east-1.amazonaws.com/Prod/"
        envkey_POSTHOG_KEY: "phc_7cmZZM8pe90nPjl2u2vPgXa6AqBjPyDhuZOZ8xcS0HX"
        envkey_POSTHOG_URL: "https://posthog.botnot.io"
        envkey_BEACON_KEY: "9bf7d9df-08ea-46fd-b82f-83ed1b05a2fa"
        directory: './'
        file_name: .env
        fail_on_empty: false
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "botnot0124"
          heroku_email: "katterine0124@gmail.com"